### ISSUE TITLE
Link to blog does not work on mobile device

### ISSUE THREAD

**Issue by SaquibShahzad** [codeprentice-org/codeprentice-org.github.io#2]
Similar problem: https://stackoverflow.com/questions/50581836/html-button-not-working-in-mobile-device#comment88291333_50582135?

Potential solution: https://stackoverflow.com/questions/22015908/onclick-not-working-on-mobile-touch/22015946#22015946

**Comment by asifmallik** [comment]
This happens because currently all the links within the nav bar are selected and when clicked it is handled by a jquery click event (see line 226 in `main.js`). The default behavior of clicking a link is prevented by `e.preventDefault()`. Then, it checks for `this.hash`, which I assume is the string including and following the "#" in the link.

So, I think the way to fix this would be to check first whether `$(hash).offset()` is undefined or not and `e.preventDefault()` based on that. Another way, and I think this may be cleaner is to use some sort of new class to define internal links and only select those links instead of all links in the nav-bar.

**Comment by SaquibShahzad** [comment]
Thanks @asifmallik , that fixed the issue. It's pushed in the latest commit!
This is the code snipped I added: 
               `if ($(hash).offset()) {
			e.preventDefault();
		};`

**Comment by asifmallik** [comment]
I think this does not fully fix the issue fully. It would still throw an error because it tries to access `$(hash).offset().top`

**Comment by SaquibShahzad** [comment]
TODO: 

- [ ] make the function return immediately if hash does not exist or wrap rest of the code in the check
